// AI insights generated by Gemini
class GeminiInsights {
  final String applianceDescription; // Description of the refrigerator
  final String groceryInsights; // Smart grocery insights
  final List<String> recipeRecommendations; // Recipe suggestions
  final String storageOptimization; // Tips for storing items
  final DateTime generatedAt; // When insights were generated

  GeminiInsights({
    required this.applianceDescription,
    required this.groceryInsights,
    required this.recipeRecommendations,
    required this.storageOptimization,
    required this.generatedAt,
  });

  factory GeminiInsights.fromGeminiResponse(String response) {
    // Parse Gemini's response into structured format
    // This is a basic parser - you can enhance it
    return GeminiInsights(
      applianceDescription: _extractSection(response, 'appliance', 'Appliance description not found'),
      groceryInsights: _extractSection(response, 'grocery', 'No grocery insights'),
      recipeRecommendations: _extractRecipes(response),
      storageOptimization: _extractSection(response, 'storage', 'No storage tips'),
      generatedAt: DateTime.now(),
    );
  }

  static String _extractSection(String text, String keyword, String fallback) {
    // Use RegExp.escape so $ in the pattern is not treated as Dart string interpolation.
    final k = RegExp.escape(keyword);
    final regex = RegExp(
      '(?:$k|recommendations?|insights?|description|tips?).*?[:\\n]\\s*(.+?)(?=\\n\\n|\\d\\.|\\z)',
      caseSensitive: false,
      dotAll: true,
    );
    final match = regex.firstMatch(text);
    return match?.group(1)?.trim() ?? fallback;
  }

  static List<String> _extractRecipes(String text) {
    final recipes = <String>[];
    final lines = text.split('\n');
    bool inRecipeSection = false;

    for (final line in lines) {
      if (line.toLowerCase().contains('recipe')) {
        inRecipeSection = true;
      }
      if (inRecipeSection && line.trim().startsWith('-')) {
        recipes.add(line.replaceFirst(RegExp(r'^[-*]\s*'), '').trim());
      }
    }

    return recipes.isNotEmpty ? recipes : ['Check Gemini response for recipes'];
  }

  @override
  String toString() =>
      'GeminiInsights(${recipeRecommendations.length} recipes, generated: $generatedAt)';
}
